

services:
  deepc:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    tty: true

  ffmpeg:
    image: mwader/static-ffmpeg:latest
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["ffmpeg"]
