# -*- coding: utf-8 -*-
"""Train Post-processing Model for FSRCNN Race Condition Compensation.ipynb

Automatically generated by Colab.
"""

# 1. Mount Google Drive (jika data disimpan di Drive)
from google.colab import drive
drive.mount('/content/drive')

# 2. Install dependencies (sebenarnya Colab sudah punya PyTorch)
#    Jika perlu versi tertentu, bisa di-uncomment
# !pip install torch torchvision

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import os
from tqdm import tqdm
import matplotlib.pyplot as plt

# 3. Tentukan path folder data (sesuaikan dengan lokasi Anda)
#    Asumsi: di Drive, folder 'data' berisi subfolder 'noisy' dan 'clean'
#    Setiap file adalah raw float32 dengan ukuran (H, W)
data_root = '/content/drive/MyDrive/fsrcnn_data/'  # ganti sesuai path Anda
noisy_dir = os.path.join(data_root, 'noisy')       # gambar rusak (race condition)
clean_dir = os.path.join(data_root, 'clean')       # gambar bersih (critical)

print("Isi noisy_dir:", os.listdir(noisy_dir) if os.path.exists(noisy_dir) else "Folder tidak ditemukan")
print("Isi clean_dir:", os.listdir(clean_dir) if os.path.exists(clean_dir) else "Folder tidak ditemukan")

# 4. Tentukan ukuran gambar (sesuaikan dengan output FSRCNN Anda)
#    Contoh: untuk QCIF (176x144) dengan scale=2, ukuran HR = 352x288
H = 288   # rows (height)
W = 352   # cols (width)


# 5. Dataset class
class FSRCNNDataset(Dataset):
    def __init__(self, noisy_dir, clean_dir, H, W, transform=None, patch_size=None):
        """
        noisy_dir: folder berisi file .yuv hasil race condition (uint8)
        clean_dir: folder berisi file .yuv hasil critical (uint8)
        H, W: tinggi dan lebar gambar (misal 288, 352)
        patch_size: jika ada, ekstrak patch acak untuk augmentasi
        """
        self.noisy_dir = noisy_dir
        self.clean_dir = clean_dir
        self.H = H
        self.W = W
        self.patch_size = patch_size
        self.transform = transform

        # Kumpulkan semua file .yuv
        self.noisy_files = sorted([f for f in os.listdir(noisy_dir) if f.endswith('.yuv')])
        self.clean_files = sorted([f for f in os.listdir(clean_dir) if f.endswith('.yuv')])

        print(f"Ditemukan {len(self.noisy_files)} file noisy, {len(self.clean_files)} file clean")

        # Baca semua frame dari setiap file
        self.noisy_frames = []
        self.clean_frames = []
        frame_size = H * W

        for f in self.noisy_files:
            path = os.path.join(noisy_dir, f)
            data = np.fromfile(path, dtype=np.uint8)
            num_frames = len(data) // frame_size
            print(f"  {f}: {num_frames} frames")
            for i in range(num_frames):
                frame = data[i*frame_size : (i+1)*frame_size].reshape(H, W).astype(np.float32) / 255.0
                self.noisy_frames.append(frame)

        for f in self.clean_files:
            path = os.path.join(clean_dir, f)
            data = np.fromfile(path, dtype=np.uint8)
            num_frames = len(data) // frame_size
            print(f"  {f}: {num_frames} frames")
            for i in range(num_frames):
                frame = data[i*frame_size : (i+1)*frame_size].reshape(H, W).astype(np.float32) / 255.0
                self.clean_frames.append(frame)

        # Pastikan jumlah frame sama (atau gunakan modulo)
        assert len(self.noisy_frames) == len(self.clean_frames), \
            f"Jumlah frame tidak sama: noisy={len(self.noisy_frames)}, clean={len(self.clean_frames)}"

        print(f"Total frame: {len(self.noisy_frames)}")

    def __len__(self):
        return len(self.noisy_frames)

    def __getitem__(self, idx):
        noisy = self.noisy_frames[idx]
        clean = self.clean_frames[idx]

        # Jika menggunakan patch, potong acak
        if self.patch_size is not None:
            ps = self.patch_size
            i = np.random.randint(0, self.H - ps + 1)
            j = np.random.randint(0, self.W - ps + 1)
            noisy = noisy[i:i+ps, j:j+ps]
            clean = clean[i:i+ps, j:j+ps]

        # Tambah dimensi channel (1 channel)
        noisy = np.expand_dims(noisy, axis=0)
        clean = np.expand_dims(clean, axis=0)

        # Konversi ke tensor float
        return torch.from_numpy(noisy).float(), torch.from_numpy(clean).float()

# 6. Definisikan model CNN pasca-proses (arsitektur sederhana)
class Compensator(nn.Module):
    def __init__(self, in_channels=1, out_channels=1, num_features=64):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Conv2d(in_channels, num_features, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(num_features, num_features, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(num_features, num_features, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(num_features, out_channels, kernel_size=3, padding=1)
        )

    def forward(self, x):
        return self.layers(x)

# 7. Hyperparameter
batch_size = 16
learning_rate = 1e-4
num_epochs = 50
patch_size = 128   # menggunakan patch untuk augmentasi data (bisa None jika gambar utuh)
num_workers = 2    # untuk DataLoader

# 8. Buat dataset dan dataloader
dataset = FSRCNNDataset(noisy_dir, clean_dir, H, W, patch_size=patch_size)
dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True, num_workers=num_workers)

# 9. Inisialisasi model, loss, optimizer
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Compensator().to(device)
criterion = nn.L1Loss()   # L1 lebih robust terhadap outlier
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# 10. Training loop
train_losses = []
for epoch in range(num_epochs):
    model.train()
    epoch_loss = 0.0
    pbar = tqdm(dataloader, desc=f'Epoch {epoch+1}/{num_epochs}')
    for noisy, clean in pbar:
        noisy, clean = noisy.to(device), clean.to(device)

        output = model(noisy)
        loss = criterion(output, clean)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item() * noisy.size(0)
        pbar.set_postfix({'loss': loss.item()})

    epoch_loss /= len(dataset)
    train_losses.append(epoch_loss)
    print(f'Epoch {epoch+1} average loss: {epoch_loss:.6f}')

    # Simpan checkpoint setiap 10 epoch
    if (epoch+1) % 10 == 0:
        torch.save(model.state_dict(), f'/content/compensator_epoch{epoch+1}.pth')

# 11. Plot loss
plt.plot(train_losses)
plt.xlabel('Epoch')
plt.ylabel('L1 Loss')
plt.title('Training Loss')
plt.show()

# 12. Simpan model akhir
torch.save(model.state_dict(), '/content/compensator_final.pth')
print("Model saved to /content/compensator_final.pth")

# 13. (Opsional) Ekspor bobot ke format teks agar bisa diimpor ke C
def export_weights_to_txt(model, filepath):
    with open(filepath, 'w') as f:
        for name, param in model.named_parameters():
            f.write(f'# {name}\n')
            param_flat = param.data.cpu().numpy().flatten()
            for val in param_flat:
                f.write(f'{val:.10f}\n')
            f.write('\n')

export_weights_to_txt(model, '/content/compensator_weights.txt')
print("Weights exported to /content/compensator_weights.txt")